definitions:     
  env_vars: &env_vars
    S3_BUCKET_NAME: cmwhitelabel # The name of your S3 bucket that have all of your clients assets.
    CLIENT_ASSETS_FOLDER: client_assets # The name of unzipped folder on the build machine that have the client assets.
    ANDROID_ASSETS_FOLDER: android_assets # The name of your folder in S3 bucket that have the client's Android assets from (/android/app/src/main/res/).
    IOS_ASSETS_FOLDER: ios_assets # The name of your folder in S3 bucket that have the client's iOS assets from (/ios/Runner/Assets.xcassets/).
  scripts:
    - &get_assets
      name: Get assets from AWS S3 bucket
      script: |
        echo "Client ID: ${CLIENT_ID}"
        curl -L "https://crm.instalytix.io/media/assets_003.zip" > "assets.zip";
        unzip assets.zip -d $CLIENT_ASSETS_FOLDER


# Builds will be triggered via Codemagic's REST API with the $CLIENT_ID variable and the WL_CLIENT_ID environment group in the payload
workflows:  
  android-client-release:
    name: Android client release
    instance_type: linux_x2
    labels:
      - ${CLIENT_ID} # Helpful when you open your Codemagic's builds page 
    environment:
      groups:
        - "client-006"
      vars:
        <<: *env_vars
    scripts:
      - *get_assets #Getting client assets from S3 bucket
      - name: Set Package name
        script: |
          flutter pub add change_app_package_name
          flutter pub run change_app_package_name:main $PACKAGE_NAME
      - name: Change Android icons
        script: cp -r ./$CLIENT_ASSETS_FOLDER/$ANDROID_ASSETS_FOLDER/* ./android/app/src/main/res
      - name: Set main image # An image that being used in this sample project
        script: cp -r ./$CLIENT_ASSETS_FOLDER/hero.png assets/hero.png
      - name: Set client id
        script: cp -r ./$CLIENT_ASSETS_FOLDER/client.env assets/client.env
      - name: Install dependencies
        script: flutter packages pub get
      - name: Flutter build aab and automatic versioning
        script: |
          BUILD_NUMBER=5
          flutter build apk --release \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER
    artifacts: 
      - build/**/outputs/**/*.a
      - test-results/flutter.json
